name: roast_track
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.1+3

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  excel: ^4.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  image: ^4.1.7
  json_serializable: ^6.7.1
  m_widget:
    git:
      url: https://github.com/BlastTea/MWidget.git
      ref: bbe3f3c440976250635e9eab1db77b919c1fd456
  open_file_plus: ^3.4.1+1
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  syncfusion_flutter_charts: ^25.1.39+1
  tflite_flutter: ^0.10.4
  webview_universal: ^0.0.5

dev_dependencies:
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
